New features
- support vim-like prefix sequences to handle indices
- use lowercase and uppercase letter to handle actions referring to
  local (view-scecific) and global indices

diff --git a/ucollage b/ucollage
--- a/ucollage
+++ b/ucollage
@@ -38,46 +38,34 @@ set_defaults() {
 }
 
 help(){
-    echo "Usage: ucollage [images]"
+    echo "Usage: ucollage [images] [directories]"
+    echo
     echo "Controls:"
-    echo "  n       get next batch of images"
-
-    echo "  N       get previous batch of images"
-
-    echo "  h       decrease number of columns by 1"
-
-    echo "  j       decrease number of lines by 1"
-
-    echo "  k       increase number of lines by 1"
-
-    echo "  l       increase number of columns by 1"
-
-    echo "  -       decrease both the numbers of columns and lines by 1"
-
-    echo "  +/=     increase both the numbers of columns and lines by 1"
-
-    echo "  s       input exact number for lines and columns"
-
-    echo "  q       exit"
-
-    echo "  m       enter monocle mode: show only one image"
-
-    echo "  M       exit monocle mode"
-
-    echo "  g       go to image number"
-
-    echo "Monocle mode specific controls:"
-
-    echo "  r       rotate image 90 degrees clockwise"
-
-    echo "  R       rotate image 90 degrees counterclockwise"
-
-    echo "  u       rotate image 180 degrees"
-
-    echo "  x       execute command (placeholders are available for common substitutions)"
-    echo "          %s - original image filename"
-    echo "          %r - rotated image filename"
-    echo "  c       rename image"
+    echo "  m/M         enter monocle mode: show only one image (equivalent to 1g/1G)"
+    echo "  Backspace   exit monocle mode"
+    echo "  n           get next batch of images"
+    echo "  N           get previous batch of images"
+    echo "  s           input exact number for lines and columns"
+    echo "  q           exit"
+    echo
+    echo "Controls with vim-like prefix counters"
+    echo "  [N]-        decrease both the numbers of columns and lines by N"
+    echo "  [N]+/=      increase both the numbers of columns and lines by N"
+    echo "  [N]h        decrease number of columns by N"
+    echo "  [N]j        decrease number of lines by N"
+    echo "  [N]k        increase number of lines by N"
+    echo "  [N]l        increase number of columns by N"
+    echo "  [N]c/C      rename image with (local/global) index N"
+    echo "  [N]g/G      go to image with (local/global) index N"
+    echo "  [N]x/X      execute command for image with (local/global) index N *"
+    echo "              placeholders are available for command execution"
+    echo "                  %s - original image filename"
+    echo "                  %r - rotated image filename"
+    echo
+    echo "Monocle mode controls:"
+    echo "  r           rotate image 90 degrees clockwise"
+    echo "  R           rotate image 90 degrees counterclockwise"
+    echo "  u           rotate image 180 degrees"
     exit
 }
 
@@ -138,6 +126,10 @@ empty_messages() {
     warning=""
 }
 
+empty_prefix() {
+    prefix=""
+}
+
 show_cursor() {
     printf "\e[?25h"
 }
@@ -194,13 +186,11 @@ show_batch() {
         # terminal lines for different window sizes. 
         # So I give it some more room for error.
         (( draw_lines = photo_lines - 3 ))
-        line_names=()
     else
         draw_lines="$photo_lines"
     fi
     for (( i = 0; i < fit_vertical; i++ ))
     do
-        [[ "$show_names" -eq 1 ]] && [[ "$show" -gt 1 ]] && names=""
         for (( j = 0; j < fit_horizontal; j++, cnt++ ))
         do
             (( index = start + i * fit_horizontal + j))
@@ -211,15 +201,6 @@ show_batch() {
                 assoc=( [action]=remove \
                         [identifier]="${fifo}${i}${j}" )
             else
-                if [[ "$show_names" -eq 1 ]] && [[ "$show" -gt 1 ]]
-                then
-                    (( current_number = i * fit_horizontal + j + 1 ))
-                    current_name="${current_number}: $(basename "${images[$index]}")"
-                    (( max_length = photo_columns - 2 ))
-                    current_name=${current_name:0:$max_length}
-                    pad_sides
-                    names+="$current_name"
-                fi
                 assoc=( [action]=add \
                         [identifier]="${fifo}${i}${j}" \
                         [path]="${images[$index]}" \
@@ -231,7 +212,6 @@ show_batch() {
             fi
             declare -p assoc > "$fifo"
         done
-        [[ "$show_names" -eq 1 ]] && [[ "$show" -gt 1 ]] && line_names+=("$names")
     done
 }
 
@@ -247,7 +227,7 @@ compute_batch() {
             #   (( start += batch))
             # to
             #   (( start += show))
-            if (( start + batch < total ))
+            if (( start + show < total ))
             then
                 rm -f "$rotated_file"
                 (( start += show ))
@@ -386,9 +366,34 @@ print_names() {
     done
 }
 
+modify_names() {
+    cnt=0
+    [[ "$show_names" -eq 0 ]] || [[ "$show" -eq 1 ]] && return 1
+    line_names=()
+    for (( i = 0; i < fit_vertical; i++ ))
+    do
+        names=""
+        for (( j = 0; j < fit_horizontal; j++, cnt++ ))
+        do
+            (( index = start + i * fit_horizontal + j))
+            if [[ "$cnt" -lt "$show" ]]
+            then
+                (( current_number = i * fit_horizontal + j + 1 ))
+                current_name="${current_number}: $(basename "${images[$index]}")"
+                (( max_length = photo_columns - 2 ))
+                current_name=${current_name:0:$max_length}
+                pad_sides
+                names+="$current_name"
+            fi
+        done
+        line_names+=("$names")
+    done
+    return 0
+}
+
 update_names() {
     clear_names
-    [[ "$show_names" -eq 1 ]] && [[ "$show" -gt 1 ]] && print_names
+    modify_names && print_names
 }
 
 redraw() {
@@ -439,20 +444,21 @@ print_info() {
         info+=" - Photos [$begin - $finish] of $total"
     else
         ((begin = start + 1))
-        info+=" - Photo $begin of $total - ${images[$start]}"
+        info+=" - Photo $begin of $total - $(basename "${images[$start]}")"
     fi
+    [[ -n "$prefix" ]] && info+=" ($prefix)"
     printf "%s" "$info"
 }
 
 in_monocle() {
-    [[ "$batch" -gt 1 ]] && warning="${1} option available for single images. Press [m] to enter monocle mode" && return 1
-    return 0
+    [[ "$batch" -eq 1 ]] && return 0
+    [[ -n "$1" ]] && warning="${1} option available for single images. Press [m] to enter monocle mode"
+    return 1
 }
 
 rotate() {
     ! in_monocle "Rotate" && return
     ! command -v convert &> /dev/null && error="imagemagick not installed: required for rotation of images" && return
-    ! command -v basename &> /dev/null && error="basename not installed: required for rotation of images" && return
     rotated_file="${tmp_dir}/rotated-$(basename "${images[$start]}")"
     [[ ! -f "$rotated_file" ]] && cp "${images[$start]}" "$rotated_file"
     convert -rotate "$1" "$rotated_file" "$rotated_file"
@@ -487,41 +493,81 @@ eval_cmd() {
     return 1
 }
 
+valid_index() {
+    if [[ "$scope" == "global" ]]
+    then
+        [[ "$image_index" -gt 0 ]] && [[ "$image_index" -le "$total" ]] && return 0
+        set_error "index" "${image_index}: valid in range [1, $total]" && return 1
+    else
+        [[ "$image_index" -gt 0 ]] && [[ "$image_index" -le "$show" ]] && return 0
+        set_error "index" "${image_index}: valid in range [1, $show]" && return 1
+    fi
+}
+
+set_image_index() {
+    if in_monocle
+    then
+        [[ -n "$prefix" ]] && warning="Prefix not supported in monocle mode" && return 1
+        image_index="$start"
+        return 0
+    else
+        if [[ -n "$prefix" ]]
+        then
+            image_index="$prefix"
+        else
+            get_input "Give $scope index to $1: "
+            [[ "$input" == "ESCAPE" ]] && return 1
+            image_index="$input"
+        fi
+        valid_index && (( image_index -= 1 )) && return 0 || return 1
+    fi
+}
+
 execute() {
-    ! in_monocle "Execute" && return
+    ! set_image_index "execute" && return 1
+    [[ "$scope" == "local" ]] && (( image_index = start + image_index))
+    clear_status
     get_input "Command (add %s for the current file): "
-    [[ "$input" == "ESCAPE" ]] && return
-    cmd=${input//%s/${images[$start]}}
+    [[ "$input" == "ESCAPE" ]] && return 1
+    cmd=${input//%s/${images[$image_index]}}
     cmd=${cmd//%r/${rotated_file}}
     eval_cmd "Execute: \"${cmd}\"" "$cmd" "Succesful execution"
 }
 
 rename() {
-    ! in_monocle "Rename" && return
-    printf "Old name: %s\n" "${images[$start]}"
+    ! set_image_index "rename" && return 1
+    [[ "$scope" == "local" ]] && (( image_index = start + image_index))
+    clear_status
+    printf "Old name: %s\n" "${images[$image_index]}"
     get_input "New name: "
-    [[ "$input" == "ESCAPE" ]] && return
-    cmd="mv ${images[$start]} $input"
-    eval_cmd "Rename to: \"${input}\"" "$cmd" "Succesfully renamed" && images[$start]="$input"
+    [[ "$input" == "ESCAPE" ]] && return 1
+    cmd="mv ${images[$image_index]} $input"
+    eval_cmd "Rename to: \"${input}\"" "$cmd" "Succesfully renamed" && images[$image_index]="$input"
 }
 
 goto_image() {
-    [[ "$show" -eq 1 ]] && return
-    if [[ -n "$1" ]]
+    if [[ "$1" == "--first" ]]
     then
-        input="$1"
+        image_index=1
+        if valid_index
+        then
+            (( image_index -= 1 ))
+        else
+            return
+        fi
     else
-        get_input "Go to: "
+        ! set_image_index "go to" && return
     fi
-    [[ "$input" == "ESCAPE" ]] && return
-    ! is_natural "$input" && set_error image "$input" && return
-    [[ "$input" -gt "$show" ]] && set_error image "${input}: valid in range [1, $show]" && return
-    (( start += input - 1 ))
-    wide_vertical="$fit_vertical"
-    wide_horizontal="$fit_horizontal"
+    if [[ "$scope" == "global" ]]
+    then
+        (( new_start = image_index ))
+    else
+        (( new_start = start + image_index))
+    fi
+    [[ "$show" -gt 1 ]] && wide_vertical="$fit_vertical" && wide_horizontal="$fit_horizontal"
     fit_vertical=1
     fit_horizontal=1
-    redraw
+    [[ ! "$new_start" == "$start" || "$batch" -gt 1 ]] && start="$new_start" && redraw
 }
 
 update_status() {
@@ -552,6 +598,7 @@ read_key() {
                 empty_messages
                 compute_batch next
                 show_batch
+                empty_prefix
                 update_status
                 [[ -z "$warning" ]] && update_names
                 ;;
@@ -559,6 +606,7 @@ read_key() {
                 empty_messages
                 compute_batch prev
                 show_batch
+                empty_prefix
                 update_status
                 [[ -z "$warning" ]] && update_names
                 ;;
@@ -568,29 +616,46 @@ read_key() {
                 clear_status
                 give_dimensions
                 maybe_redraw
+                empty_prefix
                 update_status
                 stty -echo
                 ;;
             +|=)
                 empty_messages
-                (( new_fit_vertical = fit_vertical + 1 ))
-                (( new_fit_horizontal = fit_horizontal + 1 ))
+                if [[ -z "$prefix" ]]
+                then
+                    (( new_fit_vertical = fit_vertical + 1 ))
+                    (( new_fit_horizontal = fit_horizontal + 1 ))
+                else
+                    (( new_fit_vertical = fit_vertical + prefix ))
+                    (( new_fit_horizontal = fit_horizontal + prefix ))
+                fi
                 maybe_redraw
+                empty_prefix
                 update_status
                 ;;
             -)
                 empty_messages
-                (( new_fit_vertical = fit_vertical - 1 ))
-                (( new_fit_horizontal = fit_horizontal -1 ))
+                if [[ -z "$prefix" ]]
+                then
+                    (( new_fit_vertical = fit_vertical - 1 ))
+                    (( new_fit_horizontal = fit_horizontal - 1 ))
+                else
+                    (( new_fit_vertical = fit_vertical - prefix ))
+                    (( new_fit_horizontal = fit_horizontal - prefix ))
+                fi
                 maybe_redraw
+                empty_prefix
                 update_status
                 ;;
-            m)
+            m|M)
+                [[ "$key" == "m" ]] && scope="local" || scope="global"
                 empty_messages
-                goto_image 1
+                goto_image --first
+                empty_prefix
                 update_status
                 ;;
-            M)
+            $'\b'|$'\x7F')
                 empty_messages
                 if [[ "$show" -eq 1 ]]
                 then
@@ -598,77 +663,117 @@ read_key() {
                     fit_horizontal="$wide_horizontal"
                     redraw
                 fi
+                empty_prefix
                 update_status
                 ;;
             k)
                 empty_messages
-                (( new_fit_vertical = fit_vertical + 1 ))
+                if [[ -z "$prefix" ]]
+                then
+                    (( new_fit_vertical = fit_vertical + 1 ))
+                else
+                    (( new_fit_vertical = fit_vertical + prefix ))
+                fi
                 (( new_fit_horizontal = fit_horizontal ))
                 maybe_redraw
+                empty_prefix
                 update_status
                 ;;
             j)
                 empty_messages
-                (( new_fit_vertical = fit_vertical - 1 ))
+                if [[ -z "$prefix" ]]
+                then
+                    (( new_fit_vertical = fit_vertical - 1 ))
+                else
+                    (( new_fit_vertical = fit_vertical - prefix ))
+                fi
                 (( new_fit_horizontal = fit_horizontal ))
                 maybe_redraw
+                empty_prefix
                 update_status
                 ;;
             l)
                 empty_messages
+                if [[ -z "$prefix" ]]
+                then
+                    (( new_fit_horizontal = fit_horizontal + 1 ))
+                else
+                    (( new_fit_horizontal = fit_horizontal + prefix ))
+                fi
                 (( new_fit_vertical = fit_vertical ))
-                (( new_fit_horizontal = fit_horizontal + 1 ))
                 maybe_redraw
+                empty_prefix
                 update_status
                 ;;
             h)
                 empty_messages
+                if [[ -z "$prefix" ]]
+                then
+                    (( new_fit_horizontal = fit_horizontal - 1 ))
+                else
+                    (( new_fit_horizontal = fit_horizontal - prefix ))
+                fi
                 (( new_fit_vertical = fit_vertical ))
-                (( new_fit_horizontal = fit_horizontal - 1 ))
                 maybe_redraw
+                empty_prefix
                 update_status
                 ;;
             r)
                 empty_messages
                 rotate 90
+                empty_prefix
                 update_status
                 ;;
             R)
                 empty_messages
                 rotate -90
+                empty_prefix
                 update_status
                 ;;
             u)
                 empty_messages
                 rotate 180
+                empty_prefix
                 update_status
                 ;;
-            x)
+            x|X)
+                [[ "$key" == "x" ]] && scope="local" || scope="global"
                 stty echo
                 empty_messages
                 clear_status
                 execute
+                empty_prefix
                 update_status
                 stty -echo
                 ;;
-            c)
+            c|C)
+                [[ "$key" == "c" ]] && scope="local" || scope="global"
                 stty echo
                 empty_messages
                 clear_status
-                rename
+                rename && ! in_monocle && update_names
+                empty_prefix
                 update_status
                 stty -echo
                 ;;
-            g)
+            g|G)
+                [[ "$key" == "g" ]] && scope="local" || scope="global"
                 stty echo
                 empty_messages
                 clear_status
                 goto_image
+                empty_prefix
                 update_status
                 stty -echo
                 ;;
+            [0-9])
+                empty_messages
+                prefix+="$key"
+                update_status
+                ;;
             $'\e'|$'\n')
                 empty_messages
+                empty_prefix
                 update_status
                 ;;
         esac
@@ -686,14 +791,15 @@ init() {
     read_key
 }
 
-! command -v ueberzug &> /dev/null && echo "Ueberzug not installed: ucollage dependency" && exit 1
+! command -v ueberzug &> /dev/null && echo "Required dependency not installed: ueberzug" && exit 1
+! command -v basename &> /dev/null && echo "Required dependency not installed: basename" && exit 1
 parse_config
 set_defaults
 [[ ! -d "$tmp_dir" ]] && mkdir -p "$tmp_dir"
 trap stop_daemon SIGINT
 trap "redraw; update_status" SIGWINCH
-stty -echo
 [[ "$1" =~ ^-h$|^--help$ ]] && help
+stty -echo
 (( first_batch = fit_vertical * fit_horizontal ))
 pre_read_images "$@"
 unset start #make sure that start is not set, makes check in read_images
